server:
  port: 8089
  error:
    include-stacktrace: never
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:

    url: ${db-url:jdbc:postgresql://dpg-cod3jmol5elc73fgk480-a.frankfurt-postgres.render.com/shop_it?useSSL=false&createDatabaseIfNotExist=true}
    username: ${db-username:admin2}
    password: ${db-password:iyXGeH74NroPHz7jWcHpHyl4ySMACgv8} #Hardcoding the password to support testing simplicity
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: warn
        sql: warn
      nodeValue: WARN
    blog: WARN


#schedulers:
#  cron: "*/10 * * * * *"