server:
  port: 8089
  error:
    include-stacktrace: never
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    url: ${db-url:jdbc:postgresql://localhost:5432/shop_it?useSSL=false&createDatabaseIfNotExist=true}
    username: ${db-username:postgres}
    password: ${db-password:1234} # Hardcoding the password to support testing simplicity
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        type:
          descriptor: TRACE
        sql: TRACE
      nodeValue: TRACE
    blog: TRACE

rsa:
  private-key: "classpath:certs/private.pem"
  public-key: "classpath:certs/public.pem"

# Overriding the openAPI url
springdoc:
  api-docs:
    path: /api-docs

#schedulers:
#  cron: "*/10 * * * * *"